title: Cassater 
author: me
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning documentation site

show_excerpts: true # set to false to remove excerpts on the homepage

